language: node_js
node_js:
- stable
services:
- postgresql
before_script:
- psql -c 'create database cli_test_db;' -U postgres
notifications:
  slack:
    secure: Q7wA5qaQs5M8Kcvvt8sLc0SSoATwfi06xfniTf7YEyjqtWSV/pX6KYEBkAaECIebhG2i7snGKjbF6UL2hbwJmlvAzsVHxtgRIJsHTneG8kSKUcvWO8F2rK1E9Pj7wpC0JuBGzUAx0BJ5ToKOtVBOQE1GpXYke/jMz32VHKfqcGrnsmCgaJ7m0Y/g2qkSSU0cSY7nZyxeQo6qk1TrrxWzhT78filw4xHNd4OjWw9VF9nM0jCgGWSvma0mwEm8bgX7X1sJHifGb4zH0oWlALNIovFBmgnYQC8116i+unpRCfRpRWnf8v6ksN5na2u71zd9tTCiurWvZC1jXbGNPYje3+lSZSB7SWrNON0cdQODfXLZzmulgplqpFQ7Bjry9FA7vqs3+E1kqdEMn5oPH8H1XekYnAJUG6WX0EfgZYnPwDkSIr/hyFpWdxKhlKEeEfxjLrS5iKIO/cMYwIWjl+t6q6JFXm/FoEi239bXLZYTwDXiHVAmBn+dXyjd0t871CyWZKUdm+6MtMHNDS2bh5iOBq0gMi/j12nvlsgT75bg3mH13NEnLKtQTAborlefoPZmUrRPHyKM9o13VqATjPZFkUkYijHf9uqibV2FeUZZjg82mhLOyfpy8926pQv3x9LmBxl1u3vQsRtTGloKa/bPJjDz58232M5eGTdhTqNRry8=
